#!/bin/bash

# pbs launching script R job:
# Uses the snow/parallel package so it runs on multiple CPUs.

#     job name:
#PBS -N tutorial_foreach_5

#     how many cpus?
#PBS -l nodes=16

#     How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:30:0

#     Name of output file:
#PBS -o tutorial_foreach_5.out

#     Environmental variables to make it work:
 
# Specify your email address to be notified of progress.
#PBS -M your_name@your_organisation.org
# To receive an email:
#       - job is abored: 'a' 
#       - job begins execution: 'b'
#       - job terminates: 'e'
#       Note: Please ensure that the PBS -M option above is set.
#
#PBS -m abe

module load R
cd $PBS_O_WORKDIR
 
#     Launching the job!

R --vanilla CMD BATCH tutorial_foreach_5.R


