#!/bin/bash

# pbs launching script R job:
# Uses the multicore package so it runs on one CPU only.
#			by Richard (Aug 2015)     

#     job name:
#PBS -N tutorial_foreach_3

#     how many cpus?
#PBS -l nodes=1:ppn=4

#     How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:30:0

#     Name of output file:
#PBS -o tutorial_foreach_3.out

#     Environmental variables to make it work:
 
# Specify your email address to be notified of progress.
#PBS -M rrothwell@v3.org.au
# To receive an email:
#       - job is abored: 'a' 
#       - job begins execution: 'b'
#       - job terminates: 'e'
#       Note: Please ensure that the PBS -M option above is set.
#
#PBS -m abe

module load R
cd $PBS_O_WORKDIR
 
#     Launching the job!

R --vanilla CMD BATCH tutorial_foreach_3.R


