#!/bin/bash

# pbs launching script R job:
# Exercises foreach using doParallel so it should be doinng cluster computing.

#     job name:
#PBS -N tutorial_foreach_2

#     how many cpus?
#PBS -l nodes=16

#     How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:30:0

# Inherit the correct environment variables
#PBS -V

#     Name of output file:
#PBS -o tutorial_foreach_2.out

#     Environmental variables to make it work:

# Specify your email address to be notified of progress.
#PBS -M your_name@your_organisation.org
# To receive an email:
#       - job is abored: 'a' 
#       - job begins execution: 'b'
#       - job terminates: 'e'
#       Note: Please ensure that the PBS -M option above is set.
#
#PBS -m abe
 
module load R
cd $PBS_O_WORKDIR
 
#     Launching the job!

R --vanilla CMD BATCH tutorial_foreach_2.R


