#!/bin/bash

# pbs launching script R job:
# Uses the multicore package so it runs on one CPU only.

#     job name:
#PBS -N foreach_3

#     how many cpus?
#PBS -l nodes=1:ppn=4

#      how much memory
#PBS -l mem=1G

#     How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:30:0

#     Name of output file:
#PBS -o tutorial_foreach_3.out
#PBS -j oe

#     Environmental variables to make it work:
 
# Specify your email address to be notified of progress.
#PBS -M your_name@your_organisation.org
# To receive an email:
#       - job is abored: 'a' 
#       - job begins execution: 'b'
#       - job terminates: 'e'
#       Note: Please ensure that the PBS -M option above is set.
#
#PBS -m abe

module load R
cd $PBS_O_WORKDIR
 
#     Launching the job!

# Sends R console to tutorial_foreach_3.Rout
#R --vanilla CMD BATCH tutorial_foreach_3.R

# OR sends R console output to std out so it can be seen at the log file viewed by qpeek.
R --vanilla < tutorial_foreach_3.R


