#!/bin/bash

# pbs launching script R job:
# Uses the snow/parallel package so it runs on multiple CPUs.

#     job name:
#PBS -N foreach_5

#     how many cpus?
#PBS -l nodes=16:ppn=8

#      how much memory
#PBS -l mem=2G

#     How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:30:0

# Inherit the correct environment variables
#PBS -V

#     Name of output file:
#PBS -o tutorial_foreach_5.out
# Join the output and error streams so we can view them together using qpeek 
#PBS -j oe

#     Environmental variables to make it work:

# Specify your email address to be notified of progress.
#PBS -M your_name@your_organisation.org
# To receive an email:
#       - job is abored: 'a' 
#       - job begins execution: 'b'
#       - job terminates: 'e'
#       Note: Please ensure that the PBS -M option above is set.
#
#PBS -m abe
 
module load R
cd $PBS_O_WORKDIR
 
#     Launching the job!

# Sends R console to tutorial_foreach_5.Rout
#R --vanilla CMD BATCH tutorial_foreach_5.R

# OR sends R console output to std out so it can be seen at the log file viewed by qpeek.
R --vanilla < tutorial_foreach_5.R
